[log]
filename = "test_db.log" 
level = "DEBUG"


[sql]
file = "temp.db" 
rdms = "sqlite"
dbapi = "pysqlite"
echo = true
pool_pre_ping = true
future = false 


[hop]
prefix = "prefix"
username = "username-1a2b3cd4"
hostname = "prefix.hostname.org"
groupname = "hopstream"
port = 1234
until_eos = false 
admin_topics = ["admin.one", "admin.two"]
list_topics = [
	"topic.one", 
	"topic.two", 
	"topic.three", 
	"admin.one", 
	"admin.two"
]	
topics = "topic.one,topic.two,topic.three"


[[msg]]
mock_topic = "topic.one"
mock_messages = [ 
		"{message: 1, topic: 'one', payload: '#first from topic.one'}",
		"{message: 2, topic: 'one', payload: '#second from topic.one'}",
		"{message: 3, topic: 'one', payload: '#third from topic.one'}"
]
[[msg]]
mock_topic = "topic.two"
mock_messages = [
		"{message: 4, topic: 'two', payload: '#first from topic.two'}",
		"{message: 5, topic: 'two', payload: '#second from topic.two'}",
		"{message: 6, topic: 'two', payload: '#third from topic.two'}"
]	
[[msg]]
mock_topic = "topic.three"
mock_messages = [
		"{message: 7, topic: 'three', payload: '#first from topic.three'}",
		"{message: 8, topic: 'three', payload: '#second from topic.three'}",
		"{message: 9, topic: 'three', payload: '#third from topic.three'}"
]








