version: '3'

networks:
  internal:
    external: false

volumes:
  dbdata: {}
  waitforit: {}

services:
  db:
    image: bitnami/postgresql:latest
    container_name: hop-archiver-db
    env_file: .env
    ports:
      - 5432:5432
    networks:
      - internal
    volumes:
      - dbdata:/bitnami/postgresql
  app-init-db:
    image: bitnami/postgresql:latest
    container_name: hop-archiver-db-init
    env_file: .env
    depends_on:
      - db
    networks:
      - internal
    command:
      - sh
      - -c
      - >
        until pg_isready \
            --username=${POSTGRESQL_USERNAME} \
            --dbname=${POSTGRESQL_DATABASE} \
            --host=db \
            --port=5432;
          do echo waiting for database;
          sleep 2;
          done;
          touch /tmp/db_ready;
    volumes:
      - waitforit:/tmp
  app:
    image: scimma/housekeeping:dev
    build:
      context: .
      args:
      - UID=${CUID}
    container_name: hop-archiver
    env_file: .env
    depends_on:
      - db
    networks:
      - internal
    command:
      - '/bin/bash'
      - '-c'
      - >
        while [[ ! -f /tmp/db_ready ]]; do
          echo waiting for db_ready...;
          sleep 2;
        done;
        bash copy_auth.sh && sleep 1000d
    volumes:
      - ./src:/root/src
      - waitforit:/tmp

