archiveDb:
  fullnameOverride: archive-db
  global:
    postgresql:
      auth:
        username: "archive"
        database: "archive"
        existingSecret: "archive-db"
        secretKeys:
          adminPasswordKey: "password-admin"
          userPasswordKey: "password-user"
          replicationPasswordKey: "password-replication"
  primary:
    persistence:
      storageClass: longhorn
      size: 10Gi
      subPath: "data"

archiveApiDb:
  fullnameOverride: archive-api-db
  global:
    postgresql:
      auth:
        ## Use the same credentials as the archive database because why not?
        username: "archive"
        database: "archive"
        existingSecret: "archive-db"
        secretKeys:
          adminPasswordKey: "password-admin"
          userPasswordKey: "password-user"
          replicationPasswordKey: "password-replication"
  primary:
    persistence:
      storageClass: longhorn
      size: 200Mi
      subPath: "data"

mongoDb:
  fullnameOverride: mongo-db
  useStatefulSet: true
  auth:
    existingSecret: "mongo-db"
    usernames:
    - dummy
    databases:
    - "SCiMMA_archive"
  collection: "SCiMMA_public"
  persistence:
    storageClass: longhorn
    size: 20Gi
    subPath: "data"

archiver:
  replicas: 1
  image:
    repository: "hub.ncsa.illinois.edu/scimma/archive-ingest"
    tag: "latest"
  deployment:
    annotations: {}
  hop:
    auth:
      existingSecret: "hop-auth"
      secretKeys:
        userNameKey: "username"
        userPasswordKey: "password"

archiveApi:
  replicas: 3
  debug: "true"
  image:
    repository: "hub.ncsa.illinois.edu/scimma/archive-api"
    tag: "latest"
  deployment:
    annotations: {}
  ingress:
    hostname: "explore.archive.scimma.org"
    basePath: "api"
    tls: true
    annotations:
      kubernetes.io/tls-acme: "true"
      traefik.ingress.kubernetes.io/router.tls: "true"
  django:
    secretKey:
      existingSecret: "archive-api"
      secretKey: "django-secret-key"
    admin:
      email: admin@localhost
      auth:
        username: "admin"
        existingSecret: "archive-api"
        secretKeys:
          adminPasswordKey: "django-admin-password"
  nginx:
    image:
      repository: "nginx"
      tag: "1.16-alpine"
      pullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 10m
        memory: 16Mi
      limits:
        cpu: 1000m
        memory: 512Mi
    securityContext:
      capabilities:
        drop:
        - ALL
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 101
      runAsGroup: 101

archiveBrowser:
  replicas: 3
  image:
    repository: "hub.ncsa.illinois.edu/scimma/archive-browser"
    tag: "latest"
  deployment:
    annotations: {}
  ingress:
    hostname: "explore.archive.scimma.org"
    basePath: ""
    tls: true
    annotations:
      kubernetes.io/tls-acme: "true"
      traefik.ingress.kubernetes.io/router.tls: "true"
