apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hop-archive-system
  namespace: argo-cd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: scimma-hop-archive-system
  project: default
  source:
    path: kubernetes/charts/hop-archive-system
    repoURL: https://github.com/scimma/archive-ingest.git
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
