[log]
filename = "output/hopstream.log" 
level = "INFO"

[SQlite]
type = "SQlite"
file = "hopstream.db"
rdms = "sqlite"
dbapi = "pysqlite"
echo = true
pool_pre_ping = true
future = false 
log-inserts-every = 1

[mock-db]
type = "mock"


[aws-dev-db]
type = "aws"
aws_db_name = "housekeeping-test-postgres"
aws_db_secret_name = "housekeeping-db-password"
aws_region_name  = "us-west-2"

###########
# storage 
###########

[S3-dev]
type = "S3"
bucket =  "scimma-housekeeping"

[mock-store]
type = "mock"


###########
# hop
###########

[mock-hop]
type = "mock"


[hop-prod]
type       = "hop"
#username  = "parvizim-3f2c2ae7"
username   = "petravic-2bc6a244"
hostname   = "kafka.scimma.org"
groupname  = "hopstream"
port       = 9092
until_eos  = false 
vetoed_topics = ["sys.heartbeat", "__consumer_offsets", "sys.heartbeat-cit"]