[log]
filename = "output/hopstream.log" 
level = "INFO"

###########
# database
###########

[mock-db]
type = "mock"


[aws-dev-db]
type = "aws"
aws_db_name = "housedevel-housekeeping-db"
aws_db_secret_name = "housedevel-housekeeping-db-password"
aws_region_name  = "us-west-2"

###########
# storage 
###########

[S3-dev]
type = "S3"
bucket =  "housedevel-scimma-housekeeping"

[mock-store]
type = "mock"
bucket =  "mock-bucket"

###########
# hop
###########

[mock-hop]
type = "mock"

[hop-dev]
type                = "hop"
hostname            = "dev.hop.scimma.org"
port                = 9092
vetoed_topics = ["sys.heartbeat", "__consumer_offsets", "sys.heartbeat-cit"]

[hop-prod]
type       = "hop"
#username  = "parvizim-3f2c2ae7"
#username   = "petravic-2bc6a244"
hostname   = "kafka.scimma.org"
groupname  = "hopstream"
aws-secret-name   =  "housedevel-housekeeping-hop-prod-credentials"
aws-secret-region =  "us-west-2"
port       = 9092
until_eos  = false 
vetoed_topics = ["sys.heartbeat", "__consumer_offsets", "sys.heartbeat-cit"]
