[log]
filename = "output/hopstream.log" 
level = "INFO"


[SQlite]
type = "SQlite"
file = "hopstream.db"
rdms = "sqlite"
dbapi = "pysqlite"
echo = true
pool_pre_ping = true
future = false 
log-inserts-every = 1

[mock-db]
type = "mock"

[mock-source]
type = "mock"

[aws-dev-db]
type = "aws"

[S3-db]
type = "S3"

[hop-test]
port = 9092


[hop]
type = "hop"
#username = "parvizim-3f2c2ae7"
username = "petravic-2bc6a244"
hostname = "kafka.scimma.org"
groupname = "hopstream"
port = 9092
until_eos = false 
admin_topics = ["sys.heartbeat", "__consumer_offsets"]