[log]
log-type = "log-tty"
#filename = "output/hopstream.log"
level = "DEBUG"

###########
# database
###########

[mock-db]
db-type = "mock"

[local-db]
db-type = "local"

[aws-dev-db]
db-type = "aws"
db-name = "hopdevel-housekeeping-db"
db-secret-name = "hopdevel-housekeeping-db-password"
db-aws-region  = "us-west-2"

###########
# storage
###########

[S3-dev]
store-type = "S3"
store-primary-bucket =  "hopdevel-scimma-housekeeping"
store-backup-bucket  =  "hopdevel-scimma-housekeeping-backup"
store-log-every = 20

[local-store]
store-type = "S3"
store-primary-bucket =  "hop-messages"
store-backup-bucket  =  "hop-messages-backup"
store-endpoint-url = "http://object-store:9000"
store-region-name = ""
store-log-every = 20

[mock-store]
store-type = "mock"
store-primary-bucket =  "hopdevel-scimma-housekeeping"
store-backup-bucket  =  "hopdevel-scimma-housekeeping-backup"
store-log-every = 1

###########
# hop
###########

[mock-hop]
hop-type = "mock"

[hop-dev]
hop-type                = "hop"
hop-hostname            = "dev.hop.scimma.org"
hop-port                = 9092
hop-vetoed-topics = ["sys.heartbeat", "__consumer_offsets", "sys.heartbeat-cit"]
hop-test-max-messages = 0

[hop-prod]
hop-type              = "hop"
hop-hostname          = "kafka.scimma.org"
hop-groupname         = "hopstream"
hop-aws-secret-name   =  "hopdevel-housekeeping-hop-prod-credentials"
hop-aws-secret-region =  "us-west-2"
hop-port              = 9092
hop-until-eos         = false
hop-vetoed-topics     = ["sys.heartbeat", "__consumer_offsets", "sys.heartbeat-cit"]
hop-test-topic        = "cmb-s4-fabric-tests.housekeeping-test"
hop-topic-refresh-interval-seconds = 300 #5 minutes
hop-test-max-messages = 0

[hop-local]
hop-type              = "hop"
hop-local-auth        = "/root/.config/hop/auth.toml"
hop-hostname          = "kafka.scimma.org"
hop-groupname         = "hopstream"
hop-port              = 9092
hop-until-eos         = false
hop-vetoed-topics     = ["sys.heartbeat", "__consumer_offsets", "sys.heartbeat-cit"]
hop-test-topic        = "gcn.notice"
hop-topic-refresh-interval-seconds = 300 #5 minutes
hop-test-max-messages = 1000

[kcat-prod]
hop-type   = "kcat"
hop-hostname   = "kafka.scimma.org"
hop-groupname  = "hopstream"
hop-port       = 9092
hoptest-topic = "cmb-s4-fabric-tests.housekeeping-test"
hop-aws-secret-name   =  "hopdevel-housekeeping-hop-prod-credentials"
hop-aws-secret-region =  "us-west-2"
hop-test-max-messages = 0
